### ISSUE TITLE
class com.google.gson.JsonObject cannot be cast to class com.shaft.api.RestActions$ParametersType

### ISSUE THREAD

**Issue by ShorouqElrakhawy** [MohabMohie/SHAFT_ENGINE#110]
**Describe the bug**
I get this error
class com.google.gson.JsonObject cannot be cast to class com.shaft.api.RestActions$ParametersType (com.google.gson.JsonObject and com.shaft.api.RestActions$ParametersType are in unnamed module of loader 'app')

also org.json.simple.JSONObject is not working

**Sample TC**
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.shaft.api.RestActions;

@Test
    public void verify(){
	Response response = createUser(
		FileActions.readFromFile(System.getProperty("jsonFolderPath") + "Users/", "createUser.json"));
}
private RestActions api;
api = new RestActions("https://reqres.in/");
public Response createUser(Object body) {
	JsonObject jsonObject = new JsonObject();
	JsonParser parser = new JsonParser();
	JsonElement jsonElement = parser.parse(body.toString());
	jsonObject = jsonElement.getAsJsonObject();
	return restObject.performRequest(RestActions.RequestType.POST, 201, "api/users", jsonObject, ContentType.JSON);
    }

[jsonfile.zip](https://github.com/MohabMohie/SHAFT_ENGINE/files/4655288/jsonfile.zip)

**Allure Report**
[generatedReport_runWithorg.json.simple.JSONObject.zip](https://github.com/MohabMohie/SHAFT_ENGINE/files/4655266/generatedReport_runWithorg.json.simple.JSONObject.zip)
[generatedReport_CastIssue.zip](https://github.com/MohabMohie/SHAFT_ENGINE/files/4655270/generatedReport_CastIssue.zip)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser [chrome]
 - Version [81.0.4044.138]

**Comment by MohabMohie** [comment]
Issue reproduced and fixed, will be pushed with the new release after creating and merging the PR

`[ReportManager] API Action [performRequest] successfully performed. With the following test data [Request Type: "POST" | Target Status Code: "201" | Service URL: "https://reqres.in/api/users" | Content Type: "application/json" | Response Time: "21066ms"]. @20-05-2020 10:43:32.0946 AM
`
