### ISSUE TITLE
Radio buttons and drop down lists cause [checkForElementVisibility] failed error but other elements are fine (in a specific website)

### ISSUE THREAD

**Issue by ShorouqElrakhawy** [MohabMohie/SHAFT_ENGINE#115]
Error: Element Action [checkForElementVisibility] failed. With the following test data [unique element matching this locator "By.id: days" is not visible.].

I'm not sure it's a bug or not
but in a specific website "http://automationpractice.com/" I get this error while locating radio button or dropdown list (despite of they are visible)
but text boxes or buttons are fine
I'm over 3 hours investigating and I couldn't figure out what's wrong

**Allure Report**
[generatedReport_20200522-194656.zip](https://github.com/MohabMohie/SHAFT_ENGINE/files/4669575/generatedReport_20200522-194656.zip)

**Sample TC**
public class test {
    public WebDriver driver;
    Faker fakeData = new Faker();  

    private By mrTitle = By.id("id_gender1");
    private By days= By.id("days");
    private By createAccountBtn = By.id("SubmitCreate");
    private By emailCreateField = By.id("email_create");
    private By firstName= By.id("customer_firstname");

    
    @Test
    public void verify() {
	enterEmailAndClickCreateAccountBtn( fakeData.internet().emailAddress());
	ElementActions.click(driver, mrTitle);
	ElementActions.type(driver, firstName, fakeData.name().firstName());
	ElementActions.select(driver, days, "3");
    }
    public void enterEmailAndClickCreateAccountBtn(String email) {
	ElementActions.type(driver, emailCreateField, email);
	ElementActions.click(driver, createAccountBtn);
    }
   
    

    @BeforeClass
    public void beforeClass() {
	driver = BrowserFactory.getBrowser();
	BrowserActions.navigateToURL(driver, "http://automationpractice.com/index.php?controller=authentication");
    }

}

**Comment by MohabMohie** [comment]
It looks like the select element is wrapped by a div [id="uniform-days"]... and hence the select element is not actually visible.

I recommend that you either interact with the visible element, or disable this optional flag to force interacting with the hidden elements.

![image](https://user-images.githubusercontent.com/19201898/82707911-4e7ecf80-9c7d-11ea-8d8c-504edb274a68.png)
