### ISSUE TITLE
ElementActions-Is Element Clickable fails action and don't return false || pass the action while the element is not enabled .

### ISSUE THREAD

**Issue by MamdouhMansour** [MohabMohie/SHAFT_ENGINE#131]
**Describe the bug**
When using isElementClickable method of ElementAction class in case of element is not enabled or not clickable it fails action and does not return false value or pass the action while the element is not enabled so web driver waits to element to be clickable where it will not as it is disabled as per attached.

**To Reproduce**
1. 	private WebDriver driver;

	private By firstName = By.id("firstname");
	private By lastName = By.id("lastname");
	private By emailAddress = By.id("email");
	private By password = By.id("password");
	private By registerButton = By.xpath("//button[contains(@class, 'register')]");
	private By checkBox1 = By.xpath("//label[@for='checkbox1']");
       
       @Test
	public void testIsButtonNotClickable() {
		driver = BrowserFactory.getBrowser();
		BrowserActions.navigateToURL(driver, "https://www.gocardi.com/register");		
		ElementActions.type(driver, firstName, "nameOne");
		ElementActions.type(driver, lastName, "nameTwo");
		ElementActions.type(driver, emailAddress, "test@gmail.com");
		ElementActions.type(driver, password, "test123456");
		Assertions.assertTrue(ElementActions.isElementClickable(driver, registerButton), AssertionType.NEGATIVE);
	}
	
2. See error

**Expected behavior**
isElementClickable returns false if element is disabled or not clicakble.

**Screenshots**
![IsELementClickable_Bug](https://user-images.githubusercontent.com/39811691/84573114-d9e01200-ad9e-11ea-8280-01b52aef80c0.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome, firefox]
 - Version [83, 77]

**Comment by MohabMohie** [comment]
Fixed by @MamdouhMansour
