### ISSUE TITLE
Script start with full screen browser then exit and continue running normal

### ISSUE THREAD

**Issue by asho30** [MohabMohie/SHAFT_ENGINE#163]
**Describe the bug**
Script start running with full screen browser then exit and continue running normal

**To Reproduce**
1. Just run any script

**Expected behavior**
Script start running with maximum screen browser.

**Screenshots**
![Snapshot 2020-07-12 12 23 14](https://user-images.githubusercontent.com/28779919/87243990-e48fd480-c43a-11ea-8a49-cdb4e769ef11.png)

[allure-results 1.zip](https://github.com/MohabMohie/SHAFT_ENGINE/files/4908436/allure-results.1.zip)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser chrome
 - Version 83.0.4103.116 (Official Build) (32-bit)

**Comment by MohabMohie** [comment]
@asho30 the attached file is corrupted, kindly attach a proper generated archive as we discussed in our call.

**Comment by magdyheiba** [comment]
I created a simple project and attached the allure Report and screenshot of this bug 
[generatedReport_20200717-145019.zip](https://github.com/MohabMohie/SHAFT_ENGINE/files/4937884/generatedReport_20200717-145019.zip)
![342](https://user-images.githubusercontent.com/38945724/87788187-379fc800-c83d-11ea-9081-5f3fd7f2d596.PNG)
