### ISSUE TITLE
Could you add select from dropdown using value in ElementActions

### ISSUE THREAD

**Issue by ShorouqElrakhawy** [MohabMohie/SHAFT_ENGINE#167]
I'm dealing with a dropdown has the same exact text in all options

**Describe the solution you'd like**
I need to use the "value" attribute by using ElementActions.select()

**Comment by MohabMohie** [comment]
the same method handles values natively... the value you provide to this method is searched and if it is found as a text or as a value it is selected.

look here for more info:
https://github.com/MohabMohie/SHAFT_ENGINE/blob/master/src/main/java/com/shaft/gui/element/ElementActions.java#L959

specially this condition:
https://github.com/MohabMohie/SHAFT_ENGINE/blob/master/src/main/java/com/shaft/gui/element/ElementActions.java#L980

kindly try it and let me know.

**Comment by MohabMohie** [comment]
Closing this issue for lack of response. Please feel free to comment and reopen it if needed.
