### ISSUE TITLE
The Properties folder is generated under the src/test/resources folder

### ISSUE THREAD

**Issue by MahmoudElSharkawy** [MohabMohie/SHAFT_ENGINE#226]
When creating a new SHAFT_Engine maven project, the Properties folder is generated under the src/test/resources folder.

**Steps To Reproduce:**
1. Create a new SHAFT_Engine maven project
2. Check the src/test/resources folder
3. We can see that the Properties folder is generated in the above path

**Expected behavior:** The Properties folder should be generated under src/main/resources folder.

![image](https://user-images.githubusercontent.com/46620378/102019616-37b8db00-3d7d-11eb-8b78-57fce2c4ffe7.png)

**Comment by MohabMohie** [comment]
Recommended to revisit folder structure entirely and move it under src/main/resources

Also recommended to enable automatically reading properties from both src/main/resources and src/test/resources to ensure backwards compatibility.
