### ISSUE TITLE
Enable the maximum performance mode but without the headless execution

### ISSUE THREAD

**Issue by MahmoudElSharkawy** [MohabMohie/SHAFT_ENGINE#241]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Enable the maximum performance mode but without the headless execution to fastly boost the execution time while opening the browser

**Describe alternatives you've considered**
Modify the properties flags to have the maximum performance I need 

**Additional context**
N/A

**Comment by MohabMohie** [comment]
Solved by @MahmoudElSharkawy
