### ISSUE TITLE
I request a feature to add capabilities instead of overriding shaft engine's

### ISSUE THREAD

**Issue by ShorouqElrakhawy** [MohabMohie/SHAFT_ENGINE#244]
**Is your feature request related to a problem? Please describe.**
The problem is I want to add a capability that disables SSL Certificates without overriding the shaft engine's
in the future, I may want to add more capabilities 

**Describe the solution you'd like**
A method I could use to add a capability without affecting shaft engine's

**Describe alternatives you've considered**
Covering all existing capabilities in Shaft properties files

**Comment by MahmoudElSharkawy** [comment]
Created a PR for a hot fix. Let's wait the review :D 
https://github.com/MohabMohie/SHAFT_ENGINE/pull/245

**Comment by MohabMohie** [comment]
Hotfix merged, awaiting minor investigation and then release.
