### ISSUE TITLE
Build Integration with Extent Reports framework to SHAFT_Engine

### ISSUE THREAD

**Issue by MahmoudElSharkawy** [MohabMohie/SHAFT_ENGINE#248]
**Is your feature request related to a problem? Please describe.**
To support Extent Reports framework and to be able to have an html emailable report.

**Describe the solution you'd like**
Build Integration with Extent Reports framework to SHAFT_Engine and to be able to generate reports with it alongside Allure Report framework.

**Describe alternatives you've considered**
N/A

**Comment by MohabMohie** [comment]
PR merged into master and will be released with the next internal release
