### ISSUE TITLE
[JSONFileManager] the reader gets empty each time you use the method getTestData() and we need to initialize it each time we use methods in the class

### ISSUE THREAD

**Issue by magdyheiba** [MohabMohie/SHAFT_ENGINE#249]
**Describe the bug**
While using JSONFileManager the reader gets empty each time you use the method getTestData() and we need to initialize it each time we use methods in the class
**To Reproduce**

1. initialize the class `JSONFileManager  JSONFileManager  = new JSONFileManager(FilePath);`
2. `JSONFileManager.getTestData("JSON path");`
3. another `JSONFileManager.getTestData("JSON path");`

**Expected behavior**
- The First line returns the value of JSONPath 
- The second line returns null although the JSONPath is correct 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows10]
 - Browser [chrome]
<img width="591" alt="19" src="https://user-images.githubusercontent.com/38945724/106911381-c0635000-670a-11eb-825d-1826e8fa65e7.PNG">
<img width="564" alt="18" src="https://user-images.githubusercontent.com/38945724/106911383-c0fbe680-670a-11eb-954d-ebbe00e9c228.PNG">

**Additional context**

**Comment by MohabMohie** [comment]
Thanks for reporting and fixing this issue @magdyheiba 🙏
