### ISSUE TITLE
ExtentReports - The @BeforeMethod annotation steps listed in the previous test logs info at the end

### ISSUE THREAD

**Issue by MahmoudElSharkawy** [MohabMohie/SHAFT_ENGINE#257]
**Describe the bug**
In the ExtentReports emailable HTML report - The @BeforeMethod annotation steps are listed in the previous test logs info at the end

**To Reproduce**
1. Execute a some test cases (more than 2) with @BeforeMethod annotations 
2. Check the Extent HTML emailable report cases info steps

**Expected behavior**
The steps of the @BeforeMethod should be inside of it's own test case info steps at first

**Screenshots** 
Test Case No.1 (No @BeforeMethod steps)
![image](https://user-images.githubusercontent.com/46620378/107967288-9a189c80-6fb5-11eb-9854-85b5d8cf563e.png)

Then after it (Test Case No.2)
![image](https://user-images.githubusercontent.com/46620378/107967404-bae0f200-6fb5-11eb-909b-40a3e1d30a6d.png)

**Desktop:**
 - OS: Windows

**Additional context**
N/A

**Comment by MohabMohie** [comment]
Closed, pending PR merge.
