### ISSUE TITLE
Support for handling all types of JavaScript Alerts

### ISSUE THREAD

**Issue by MahmoudElSharkawy** [MohabMohie/SHAFT_ENGINE#289]
**Is your feature request related to a problem?**
The scenarios which have Alerts.

**Description**
Support for handling all types of JavaScript Alerts (Normal, Confirm and prompt).

**Additional context**
N/A

**Comment by MohabMohie** [comment]
@MahmoudElSharkawy any hope for a PR to close this one? 😀

**Comment by MohabMohie** [comment]
linked to #472
