### ISSUE TITLE
"opencv_java451.dll not in any libs folder" Error when using SikuliActions to click on element

### ISSUE THREAD

**Issue by YaraHossam96** [MohabMohie/SHAFT_ENGINE#290]
**Description:**
When trying to click on an element using SikuliActions class in SHAFT, .click () function, an error occurs saying 'java.lang.ExceptionInInitializerError' and when digging more in the error details, it was found that the error cause was that there is a missing openCV dll file.

**Reproduction steps:**
1. Open a new Maven project in Eclipse.
2. Add SHAFT_ENGINE dependency in the pom.xml file.
3. Add TestNG dependency in the pom.xml file.
4. Add new Package.
5. In the package, add new TestNG class
6. Write down the following code which basically navigates to a Youtube page, then clicks on an icon on that Youtube page.

**Here is a screenshot for the sample code for recreating the steps:**
![Screenshot 2021-04-11 164730](https://user-images.githubusercontent.com/70035965/114309017-0c08f000-9ae6-11eb-8beb-37b40713cb27.png)

**Screenshot of the icon image that should be clicked after running this code (note: the image path is local, change the path according to your local storage of the image)**
![Youtube](https://user-images.githubusercontent.com/70035965/114309710-6c009600-9ae8-11eb-8019-58be9033faec.png)

**Expected behaviour:**
Expected that code should click on the attached image (Youtube icon on the up left corner).

**Screenshot of the error:**
![Screenshot 2021-04-11 165444](https://user-images.githubusercontent.com/70035965/114309744-8a669180-9ae8-11eb-9eb4-a152399731a4.png)

**Environment:**
The attached code sample was running on the following environment:
1. Operating system: Windows x64
2. Java 15,2 was used as a running environment.
3. Target browser: Chrome Version 89.0.4389.114 (Official Build) (64-bit)

**Comment by MohabMohie** [comment]
@YaraHossam96 apologies for the belated reply.

Kindly note that this issue was just fixed, it was a conflict in the SHAFT_Engine internal dependencies matrix.
Also kindly find the below proper code sample:

`    @Test
    public void sampleWithSeleniumAndYoutube() {
        WebDriver driver = BrowserFactory.getBrowser();
        BrowserActions.navigateToURL(driver, "https://www.youtube.com/watch?v=6FbpNgZ8fZ8&t=2s");
        String pathToTargetElementImage = System.getProperty("testDataFolderPath") + "sikulixElements/youtube.png";
        ElementActions.performSikuliAction().click(pathToTargetElementImage);
        Assertions.assertBrowserAttribute(driver, "url", "https://www.youtube.com/");
    }`

**Comment by MohabMohie** [comment]
![image](https://user-images.githubusercontent.com/19201898/116214002-925c3d80-a746-11eb-8ac3-9399ac58867b.png)
