### ISSUE TITLE
Add option/property to lower the size of the animated GIF

### ISSUE THREAD

**Issue by MahmoudElSharkawy** [MohabMohie/SHAFT_ENGINE#296]
**Is your feature request related to a problem?**
* Most of the time, the animated GIF generated has a big file size (alot bigger than the video recording).
* The HTML - Extent Emailable Execution Report harder to be attached on an email when we have alot of test cases in it. 

**Describe the solution you'd like**
Add option/property to lower the size of the animated GIF by sacrificing some of the images quality.

**Describe alternatives you've considered**
N/A

**Additional context**
![176615795_476615746953671_5940286204800931874_n](https://user-images.githubusercontent.com/46620378/115533297-e5da1180-a296-11eb-9f95-926978db488e.png)

**Comment by MohabMohie** [comment]
force scaled down to 720p for now
before:
![image](https://user-images.githubusercontent.com/19201898/116225913-aa39be80-a752-11eb-8be4-5860196459e7.png)

after:
![image](https://user-images.githubusercontent.com/19201898/116225956-b7ef4400-a752-11eb-887f-89b3bd2f27fa.png)

closed by #303
