### ISSUE TITLE
Screenshot are not added in the report and Unsported error are not handled 

### ISSUE THREAD

**Issue by muhammmedkhattab** [MohabMohie/SHAFT_ENGINE#301]
**Describe the bug**
Create a flow using Android ,appium on emulator 

Expected: screenshot should be added with no errors in the report 

Actual:

Logs:

 rg.openqa.selenium.UnsupportedCommandException:
 Method is not implemented
 Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
 System info: host: 'C02CM11EMD6V', ip: 'fe80:0:0:0:10dc:20a2:b776:6f91%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.6', java.version: '14.0.2'
 Driver info: io.appium.java_client.android.AndroidDriver
 Capabilities {appActivity: de.check24.c24.DebugConfigA..., appPackage: de.c24.bankapp.develop, automationName: UiAutomator2, databaseEnabled: false, desired: {appActivity: de.check24.c24.DebugConfigA..., appPackage: de.c24.bankapp.develop, automationName: UiAutomator2, deviceName: emulator-5554, platformName: android, platformVersion: 10, udid: emulator-5554}, deviceApiLevel: 29, deviceManufacturer: Google, deviceModel: Android SDK built for x86, deviceName: emulator-5554, deviceScreenDensity: 440, deviceScreenSize: 1080x2220, deviceUDID: emulator-5554, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, pixelRatio: 2.75, platform: LINUX, platformName: Android, platformVersion: 10, statBarHeight: 66, takesScreenshot: true, udid: emulator-5554, viewportRect: {height: 2022, left: 0, top: 66, width: 1080}, warnings: {}, webStorageEnabled: false}
 Session ID: 6e11728b-f25a-4c25-8d24-9b245aa17bc8
 java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
 java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
 org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
 org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
 org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
 org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
 io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:247)
 org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
 io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
 io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
 io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
 org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:489)
 com.shaft.gui.element.ElementActions.performHover(ElementActions.java:1319)
 java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 java.base/java.lang.reflect.Method.invoke(Method.java:564)
 org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
 org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
 org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
 org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
 org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
 org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
 org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
 org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
 java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
 org.testng.TestRunner.privateRun(TestRunner.java:764)
 org.testng.TestRunner.run(TestRunner.java:585)
 org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
 org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
 org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
 org.testng.SuiteRunner.run(SuiteRunner.java:286)
 org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
 org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
 org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
 org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
 org.testng.TestNG.runSuites(TestNG.java:1069)
 org.testng.TestNG.run(TestNG.java:1037)
 com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)

Logs:

org.openqa.selenium.UnsupportedCommandException:
‘style’ attribute is unknown for the element. Only the following attributes are supported: [checkable, checked, {class,className}, clickable, {content-desc,contentDescription}, enabled, focusable, focused, {long-clickable,longClickable}, package, password, {resource-id,resourceId}, scrollable, selection-start, selection-end, selected, {text,name}, bounds, displayed, contentSize]
Build info: version: ‘3.141.59’, revision: ‘e82be7d358’, time: ‘2018-11-14T08:17:03’
System info: host: ‘C02CM11EMD6V’, ip: ‘fe80:0:0:0:10dc:20a2:b776:6f91%en0’, os.name: ‘Mac OS X’, os.arch: ‘x86_64’, os.version: ‘10.15.6’, java.version: ‘14.0.2’
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {appActivity: de.check24.c24.DebugConfigA..., appPackage: de.c24.bankapp.develop, automationName: UiAutomator2, databaseEnabled: false, desired: {appActivity: de.check24.c24.DebugConfigA..., appPackage: de.c24.bankapp.develop, automationName: UiAutomator2, deviceName: emulator-5554, platformName: android, platformVersion: 10, udid: emulator-5554}, deviceApiLevel: 29, deviceManufacturer: Google, deviceModel: Android SDK built for x86, deviceName: emulator-5554, deviceScreenDensity: 440, deviceScreenSize: 1080x2220, deviceUDID: emulator-5554, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, pixelRatio: 2.75, platform: LINUX, platformName: Android, platformVersion: 10, statBarHeight: 66, takesScreenshot: true, udid: emulator-5554, viewportRect: {height: 2022, left: 0, top: 66, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: 6e11728b-f25a-4c25-8d24-9b245aa17bc8
java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:247)
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:45)
io.appium.java_client.MobileElement.execute(MobileElement.java:1)
io.appium.java_client.android.AndroidElement.execute(AndroidElement.java:1)
org.openqa.selenium.remote.RemoteWebElement.getAttribute(RemoteWebElement.java:134)
com.shaft.gui.image.ScreenshotManager.highlightElementAndReturnDefaultStyle(ScreenshotManager.java:464)
com.shaft.gui.image.ScreenshotManager.internalCaptureScreenShot(ScreenshotManager.java:344)
com.shaft.gui.image.ScreenshotManager.captureScreenShot(ScreenshotManager.java:121)
com.shaft.gui.element.ElementActions.takeScreenshot(ElementActions.java:960)
com.shaft.gui.element.ElementActions.click(ElementActions.java:130)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:564)
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
org.testng.TestRunner.privateRun(TestRunner.java:764)
org.testng.TestRunner.run(TestRunner.java:585)
org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
org.testng.SuiteRunner.run(SuiteRunner.java:286)
org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
org.testng.TestNG.runSuites(TestNG.java:1069)
org.testng.TestNG.run(TestNG.java:1037)
com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)

![20210426_155142](https://user-images.githubusercontent.com/36113228/116094077-84a3ab00-a6a7-11eb-8cfc-e830b9c56b22.jpg)

**Comment by MohabMohie** [comment]
Please note that the above combination means that there are 2 issues.
1. Please make sure that you're using Artificial intelligence for element highlighting. Use the configuration manager after upgrading to the latest version of shaft engine.
2. Do not use the Click method for native mobile elements please, you should use TouchActions.tap instead.

**Comment by MohabMohie** [comment]
closed due to inactivity.
