### ISSUE TITLE
[ER] Validations step to be nested inside the customLogMessage parameter step in the Allure report

### ISSUE THREAD

**Issue by MahmoudElSharkawy** [MohabMohie/SHAFT_ENGINE#309]
Validations steps to be nested inside the customLogMessage parameter step in the Allure report instead of making two steps

**Comment by MohabMohie** [comment]
@MahmoudElSharkawy Does this meet your expectations from this feature request?
![image](https://user-images.githubusercontent.com/19201898/121749890-b794e780-cb0b-11eb-961f-aff53d8fd72c.png)

Code:
![image](https://user-images.githubusercontent.com/19201898/121749993-d2fff280-cb0b-11eb-895c-c28016ababdf.png)

**Comment by MahmoudElSharkawy** [comment]
@MohabMohie 
This is great! I would like to suggest that the stepLog to be as a nested step inside the custom log message. What do you think?
![image](https://user-images.githubusercontent.com/46620378/121750590-f4151300-cb0c-11eb-849e-fdbec4bdc504.png)

**Comment by MohabMohie** [comment]
it will always be one step nested inside the other... after seeing it, it didn't look good actually.
that's why I believed that it makes sense to be at a lower level than a full step... relegating it to a mere log point... as the business description replaces it as the main step text.
