### ISSUE TITLE
Support for sending Graphql API Request (without repetitive steps).

### ISSUE THREAD

**Issue by hammad101088** [MohabMohie/SHAFT_ENGINE#311]
Any possible graphql request consists of the following:
- "Query or mutation"

1. query:
`{
  company {
    ceo
    cto
    coo
  }
}`

- "Query or mutation" and variables

1. mutation:
`
mutation ($name:String,$rocket:String){
  insert_users(objects: {name:$name, rocket: $rocket}) {
    returning {
      name
      rocket
      id
    }
  }
}
`

2. variables:
`{
  "name": "test",
  "rocket": "test"
}`

- "Query or mutation", variables, and fragments

1. query:
`query ($firatName:String!,$lastName:String!){
  dummyTest(input:{phone:$phone}){
    ...userField
  }
}`
2. variables:
`{
  "firatName":  "test",
  "lastName":  "test"
}`
3. fragment
`fragment userField on User{
  id
  firstName
  lastName
}`

There were some repetitive steps while performing a Graphql API request.
For me, to overcome this problem, I've used a utility package with GraphqlActions class.

I'd like to suggest the following:
- common method for any graphql request.
- overload this method with different parameters for each possible case (listed above).

**Comment by MohabMohie** [comment]
Thanks for sharing this @hammad101088 would you like to work on implementing this utilities class within the API package?

**Comment by hammad101088** [comment]
I'd be glad to contribute. @MohabMohie

**Comment by MohabMohie** [comment]
Kindly join the slack channel and let me know if you need any help.

Feel free to create a PR at your convenience. 👍

**Comment by MohabMohie** [comment]
@hammad101088 awaiting your PR to close that issue :)
