### ISSUE TITLE
The "mobile_app" property to be enhanced to work with relative path of the project

### ISSUE THREAD

**Issue by MahmoudElSharkawy** [MohabMohie/SHAFT_ENGINE#345]
**Is your feature request related to a problem? Please describe.**
For more user friendly system, we would like the mobile_app property to support and work with the  relative path of the project.

**Describe the solution you'd like**
We can do some post processing on the property and if it's a relative path, then append the absolute path to it; and if not, leave it as is.

**Describe alternatives you've considered**
Use the setProperty method in @BeforeClass like this: 
`System.setProperty("mobile_app", FileActions.getAbsolutePath("relativePath/to/myApp/", "myApp.apk"));`

**Additional context**
N/A

**Comment by MohabMohie** [comment]
![image](https://user-images.githubusercontent.com/19201898/131833820-6f5089ab-fa6e-4083-9e0f-cda90636e1d6.png)
