### ISSUE TITLE
[RestAPI] Add Request and Response specs as attachments to allure report

### ISSUE THREAD

**Issue by khaledskhamis** [MohabMohie/SHAFT_ENGINE#360]
Request body and response body are not included in the allure report

**Comment by MohabMohie** [comment]
Body is attached correctly, but nothing is attached in case of form or query parameters.

It would add more value to have the entire specs for the request and response attached in the allure report in addition to the json/xml/binary body of the response.

**Comment by MohabMohie** [comment]
![image](https://user-images.githubusercontent.com/19201898/131831882-0bd54472-657f-4799-b54d-d247f24886f6.png)
added a new attachment for request specifications which includes all headers, form parameters, and query parameters.
