### ISSUE TITLE
[Allure Report with Cucumber ] when we use @BeforeStep the output at the report is not formated like given/when/then annotations

### ISSUE THREAD

**Issue by magdyheiba** [MohabMohie/SHAFT_ENGINE#366]
**Describe the bug**
when we use @BeforeStep the output at the report is not formated like given/when/then annotations
**To Reproduce**
1. create simple BDD script 
2. add @BeforeStep anotation 
3. run your script and check allure report

**Expected behavior**
@beforeStep should be formated like given/when/then
**Screenshots**
![shaft2](https://user-images.githubusercontent.com/38945724/130461362-103b5eb3-c600-464a-bf66-277894b249aa.png)

**Comment by MohabMohie** [comment]
@magdyheiba any news? Do you need any support?

**Comment by MohabMohie** [comment]
reproduced case on local testing environment... preparing to fix.
![image](https://user-images.githubusercontent.com/19201898/139724559-be9132dd-aefb-43b5-b110-a450e5a8166b.png)

fix will be to remove the steps completely from the summary to match the native cucumber report
![image](https://user-images.githubusercontent.com/19201898/139724701-331d6eb2-e37e-4e5c-9bac-3494ecdae9b7.png)

**Comment by MohabMohie** [comment]
fixed
![image](https://user-images.githubusercontent.com/19201898/139725362-91b872f0-d781-436f-a630-647ac652200b.png)
