### ISSUE TITLE
[PDF Validations] Add support to validate pdf files content

### ISSUE THREAD

**Issue by MohabMohie** [MohabMohie/SHAFT_ENGINE#369]
Investigate this solution and add a new validation for it
https://pdfbox.apache.org/

**Comment by MamdouhMansour** [comment]
Will try to use apache pdfbox library to validate pdf document content.[https://www.lambdatest.com/blog/selenium-testing-pdf-files/](url)

**Comment by MohabMohie** [comment]
Closed by #386
