### ISSUE TITLE
[RestAPI] perform performance and load testing

### ISSUE THREAD

**Issue by MamdouhMansour** [MohabMohie/SHAFT_ENGINE#370]
This is new feature that need more research

**Comment by MohabMohie** [comment]
@MamdouhMansour so far my research says that there will be major reporting challenges and that the best approach is to route the rest assured tests through jmeter proxy to record them and then playback and control the frequency of the tests from jmeter.

Did you find something better or shall we close this ticket?

**Comment by MamdouhMansour** [comment]
@MohabMohie  I did quick search and didn't find anything that can be done in this part. I think we can close it now and if found something will open a new ticket.
