### ISSUE TITLE
Can't send Rest API Request with mutli-part form parameter data

### ISSUE THREAD

**Issue by MamdouhMansour** [MohabMohie/SHAFT_ENGINE#383]
**Describe the bug**
Couldn't send a post request with a request body that has form parameters.
Engine couldn't know how to parse this form parameter.

**To Reproduce**
1. Check the code used with SHAFT that have produced the issue
2. Check the code used with REST ASSURED that worked fine
3. Check the error highlighted in the screen shot attached

**Expected behavior**
SHAFT should be able to send the request with multi-part form paramater

**Screenshots**
![image](https://user-images.githubusercontent.com/39811691/133248093-9c90a4a0-477e-4312-b4d4-382e58e23f41.png)
![image](https://user-images.githubusercontent.com/39811691/133248159-03e72e5b-d771-42b3-a784-03b4a69c6c48.png)

Here are the code samples used to connect to App-Center and get the latest build-->

SHAFT code sample-->
		Response browserStackResponse = browserStackRestApi.buildNewRequest("", RequestType.POST)
				.setAuthentication(System.getProperty("Username"), System.getProperty("Password"),
						AuthenticationType.BASIC)
				.setContentType(ContentType.MULTIPART)
				.setParameters(Arrays.asList(Arrays.asList("url", download_url)), ParametersType.FORM).performRequest();

REST ASSURED code sample that working fine -->
		Response browserStackResponse = RestAssured.given().contentType(ContentType.MULTIPART).auth().preemptive()
				.basic(System.getProperty("Username"), System.getProperty("Password")).multiPart("url", download_url)
				.log().all().when().log().all().post(System.getProperty("BrowserStack_Uri")).then().statusCode(200)
				.log().all().extract().response();

**Comment by MohabMohie** [comment]
closed due to inactivity, feel free to reopen with answers to the above.
