### ISSUE TITLE
The video attachement is not processed when using Mobile Testing

### ISSUE THREAD

**Issue by sys123-data** [MohabMohie/SHAFT_ENGINE#387]
**Describe the bug**
The video attachement is not processed when using Mobile Testing

The encoding method is only effective for web at the moment, but the mobile recording gets attached directly without any post processing as per this line of code.

https://github.com/MohabMohie/SHAFT_ENGINE/blob/cd6e88490b6825e6416f6775c3b9cf5edd6a0d91/src/main/java/com/shaft/gui/video/RecordManager.java#L94

**Comment by MohabMohie** [comment]
Closed by #394
