### ISSUE TITLE
The highlight of elements in IOS screenshots is missplaced.

### ISSUE THREAD

**Issue by sys123-data** [MohabMohie/SHAFT_ENGINE#422]
The highlight of elements in IOS screenshots is missplaced.

**Comment by MohabMohie** [comment]
@sys123-data 
This is a screenshot after merging the latest fix iOS running on Mac, any idea where the problem is?
![image](https://user-images.githubusercontent.com/19201898/139648368-fd246b15-7a72-4ef9-8336-273acf8d5154.png)
