### ISSUE TITLE
Video Recorder Captured screen itself not Execution window 

### ISSUE THREAD

**Issue by zanoon2020** [MohabMohie/SHAFT_ENGINE#463]
**Describe the bug**
During test execution screen recorder captures the laptop screen not the execution window after minimizing execution window 

**To Reproduce**
1. run any test method 
2. when chrome instance open minimize it or move it to another screen 
3. wait until executing finish 
4. check allure report screen record 

**Expected behavior**
Video Recorder must capture execution window not laptop screen 

**Desktop (please complete the following information):**
 - OS: [WIN 10]
 - Browser [chrome]
 - Version [96.0.4664.45]

**Comment by MohabMohie** [comment]
This is working as designed. There is currently no known way to record just the screen. Kindly share if you know a way.
