### ISSUE TITLE
click webview inside native app

### ISSUE THREAD

**Issue by sys123-data** [MohabMohie/SHAFT_ENGINE#464]
ElementActions(driver).click(element_locator) is not working for Android Native App when element_locator provided is inside an webview rendered by native app.

**Comment by MohabMohie** [comment]
This is confirmed as a bug, after the latest update the click action redirects to touchactions.tap, which doesn't work for webviews.

**Comment by MohabMohie** [comment]
Fixed, to be released in the next version.
