### ISSUE TITLE
Add URLEncoding restAssured function

### ISSUE THREAD

**Issue by khaledskhamis** [MohabMohie/SHAFT_ENGINE#467]
**Is your feature request related to a problem? Please describe.**
When I send API request with urlArgument contain special character the special characters encoded and fail the request

**Describe the solution you'd like**
add URLEncoding flag to be able to disable it

**Describe alternatives you've considered**
automatically disable the encoding

**Additional context**

**Comment by MohabMohie** [comment]
Closed by #468
