### ISSUE TITLE
Video recording is not generated when I run android native app and the "test method" for video recording scope is enabled.

### ISSUE THREAD

**Issue by samiir95** [MohabMohie/SHAFT_ENGINE#475]
When you update this property >> "videoParams_scope=TestMethod"  in the "VisualValidations.properties" file >> then you run your tests using maven >> and open the generated allure report to check the video recording, nothing is there.

**Comment by MohabMohie** [comment]
Screenshot the allure report please and kindly make sure to expand the aftermethod and afterclass if any.

**Comment by samiir95** [comment]
> Screenshot the allure report please and kindly make sure to expand the aftermethod and afterclass if any.

![image](https://user-images.githubusercontent.com/38625749/146257907-a05a3f10-f6c0-46bf-91ba-52f3fe2bca37.png)

**Comment by MohabMohie** [comment]
can you kindly confirm that this issue is still existing in the latest engine release?
if so, kindly attach the full execution log file here.

**Comment by hernandezmshawntae** [comment]
Please and Thank You.

**Comment by hernandezmshawntae** [comment]
https://github.com/MohabMohie privacy concerns please and thank you

**Comment by hernandezmshawntae** [comment]
https://github.com/MohabMohie privacy concerns please and thank you

**Comment by MohabMohie** [comment]
will close this issue due to lack of activity for the past week, but kindly feel free to reopen it and keep the conversation going.
