### ISSUE TITLE
Tap element by image shows as passed while the element is not tapped in some cases where a delay needs to be introduced

### ISSUE THREAD

**Issue by NoraAhmedVodafone** [MohabMohie/SHAFT_ENGINE#482]

**Comment by MohabMohie** [comment]
solved with the latest release.
introduced matching accuracy, retries, and three new algorithms for element identification.
will fail if all three attempts didn't find the element and will attach both the reference and current screenshots, instructing the user to either fix the scenario or crop the current screenshot to get a valid reference image

![image](https://user-images.githubusercontent.com/19201898/147928592-07993af0-5b74-4bcf-9404-1c9bcf6a130f.png)
