### ISSUE TITLE
Add support for Database type  Oracle using Service Name / Provide a custom connection string for Database connection 

### ISSUE THREAD

**Issue by ashaban86** [MohabMohie/SHAFT_ENGINE#487]
**Is your feature request related to a problem? Please describe.**
When connect to Oracle Database using Service name, getting exception 
```
Caused by: java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor 
```

**Describe the solution you'd like**

split the ORACLE database type to 2 types **ORACLE_SID** and **ORACLE_SERVICE_NAME**

```
  public enum DatabaseType {
        MY_SQL, SQL_SERVER, POSTGRE_SQL, ORACLE_SID ,ORACLE_SERVICE_NAME, IBM_DB2
    }
```
then in createConnection method add the 2 cases instead of 1 case  ORACLE

```
  case ORACLE_SID -> {
                	connectionString = "jdbc:oracle:thin:@" + dbServerIP + ":" + dbPort + ":" + dbName;
                }

case ORACLE_SERVICE_NAME-> {
                	connectionString = "jdbc:oracle:thin:@" + dbServerIP + ":" + dbPort + "/" + dbName;
                }
```
**Describe alternatives you've considered**
 Provide a custom connection string for Database connection

**Comment by hernandezmshawntae** [comment]
Please and Thank You.

**Comment by MohabMohie** [comment]
will be merged in the next release.
