### ISSUE TITLE
there is issue when using (Tap and click) method with Appium

### ISSUE THREAD

**Issue by amrelgarhi6** [MohabMohie/SHAFT_ENGINE#501]
**Describe the bug**
there is an issue when using (Tap and click) method with Appium, Although the test case is successful, it is noticed that no action occurs, and I'm sure that locator is right because I'm using it with my native selenium

**To Reproduce**
1. Connect to Appium Server
2. Open the emulator
3. Run the test case

**Expected behavior**
Depending on the test case set, and what appears in the console with the success of the test case, there must be a change that occurred

**Actual Result**
The test case has passed but there is no action happened

**Smartphone (please complete the following information):**
 - Device: Pixel4XL
 - OS: Android 10.0

**Additional context**
I'm using the latest version of Appium and Shaft Engine

**Comment by MohabMohie** [comment]
Can you kindly confirm that this issue is still ongoing and mention the version number for the Engine you're using?

**Comment by MohabMohie** [comment]
Implemented blind fix for the issue due to lack of feedback.
