### ISSUE TITLE
More Detailed Documentation (especially for new features/classes like 'Validations')

### ISSUE THREAD

**Issue by MahmoudSaleh97** [MohabMohie/SHAFT_ENGINE#507]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to add a method or some sort of validation (complex or simple) but due to the lack of info/documentation, it takes a lot of time and You end up doing it with some basic old native selenium methods/validations

**Describe the solution you'd like**
I guess if there's much more detailed about each feature/class/interface/method with complete explanation/description will make the process easier 

**Describe alternatives you've considered**

**Additional context**
Please, Please, Please, Don't get me wrong, There are some videos which are great from Eng: Mohab & Eng El-Sharkawy and they are great to setup and even in some cases enough to proceed on a real-life main project, but there's something still missing which in my case more description, details and info about each and every little thing (of course this will take some time, May Allah be with you)

**Comment by MohabMohie** [comment]
Thank you for this.
Can you kindly help us even more by listing specific methods that you struggle with? It would give us a good place to start!

**Comment by MohabMohie** [comment]
Will close this issue as we work more on the user guide.
