### ISSUE TITLE
Can't Set Proxy Settings in Browser session using SHAFT

### ISSUE THREAD

**Issue by AmrAdelElkholy** [MohabMohie/SHAFT_ENGINE#511]
**Describe the bug**
Can't set a proxy setting in browser session through SHAFT or SHAFT properties.

**To Reproduce**
1. Use a machine behind a proxy
2. Check SHAFT Property files to add proxy settings

**Expected behavior**
Proxy setting can be set through property file

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - Version Any
 - Network: Behind a reverse proxy

**Comment by MohabMohie** [comment]
closed by #556
