### ISSUE TITLE
Unable to use ElementActions.type to send text to android app

### ISSUE THREAD

**Issue by bourhamJR** [MohabMohie/SHAFT_ENGINE#533]
**Describe the bug**
when i try to send text to text field in android device (developed with flutter), i got error that 'textcontent' attribute is unknown for the element, however if i use native selenium sendKeys, text is sent successfully with no issue.
 
**Expected behavior**
Android driver to send text to the required text field

**Screenshots**

![274491620_10161600029143332_4133222563979211680_n](https://user-images.githubusercontent.com/92738197/155291957-14ef0af6-de7d-4483-a550-c171b75828ef.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi 
 - Device model: M2101K6G
 - OS: Android 
 - Version : 11

**Comment by MohabMohie** [comment]
Issue has been fixed and will be pushed with the next release.

For now, you can disable this property from the configuration manager (https://mohabmohie.github.io/SHAFT_ENGINE/)
Flags > Force check text was typed correctly
![image](https://user-images.githubusercontent.com/19201898/158050069-69ab181e-679e-4c93-9503-1e327ce5e628.png)
