### ISSUE TITLE
I have received a request to read the whole response body from the JSONFileManager

### ISSUE THREAD

**Issue by magdyheiba** [MohabMohie/SHAFT_ENGINE#537]
**Is your feature request related to a problem? Please describe.**
If we use the JSONFileManager and there is a need to read the whole response to assert it with the actual response came from restAssured you'll need to add some sort of code / utils in addition to JSONFileManager class

**Describe the solution you'd like**
I will add a function to get the whole response by calling it

**Comment by MohabMohie** [comment]
you can already use the validation wizard to compare against a local json file, and in case you want to read any file as a string or byte array you can use FileActions.
