### ISSUE TITLE
screenshot swipe

### ISSUE THREAD

**Issue by sys123-data** [MohabMohie/SHAFT_ENGINE#584]
If I am in thee same page with the image source test pass and no swipe is executed as it should be.
But if I am not there the swipe is executed but fails to pass the test(no screenshot of final app state is taken).

https://user-images.githubusercontent.com/68052609/162442024-7720a302-73b3-4bc8-b352-3d967bc7e84a.mp4

[logs.txt](https://github.com/MohabMohie/SHAFT_ENGINE/files/8452027/logs.txt)

**Comment by MohabMohie** [comment]
have you tried this cropping the attached screenshot? "Screenshot - 1649421896799_clickLogInSilver_swipeElementIntoView - Current Screen Image_passed"

[ReportManager] Element Action [SwipeElementIntoView] failed. With the following test data [1Couldn't find reference element on the current screen. If you can see it in the attached image then kindly consider cropping it and updating your reference image.]. @08-04-2022 15:44:57.0649 pm
[ReportManager] Successfully created attachment [Screenshot - 1649421897638_clickLogInSilver_swipeElementIntoView - Reference Screenshot_passed] @08-04-2022 15:44:57.0650 pm
[ReportManager] Successfully created attachment [Screenshot - 1649421896799_clickLogInSilver_swipeElementIntoView - Current Screen Image_passed] @08-04-2022 15:44:57.0651 p
