### ISSUE TITLE
Switch To New Tab Feature 

### ISSUE THREAD

**Issue by magdyheiba** [MohabMohie/SHAFT_ENGINE#585]
**Is your feature request related to a problem? Please describe.**
New Feature at selenium 4 to be written with Shaft Syntax

**Describe the solution you'd like**
implement the syntax to be more user friendly 

**Describe alternatives you've considered**

**Comment by MohabMohie** [comment]
closed by #586

**Comment by Ghadeermoh** [comment]
I need new  Validation for equalFileIgnoringOrder  , As I can't validate response with Json file when Order of returned values change in each request 
Thanks
