### ISSUE TITLE
Since latest version The Browser Options isn't working (Ex: ChromeOptions)

### ISSUE THREAD

**Issue by sarahelghayaty** [MohabMohie/SHAFT_ENGINE#612]

**Comment by MohabMohie** [comment]
Can you share some sample code please and details (what's the expected and what's the actual behavior)

**Comment by sarahelghayaty** [comment]
driver = DriverFactory.getDriver(DriverType.DESKTOP_CHROME,getChromeConfiguration());

	private static ChromeOptions getChromeConfiguration() {
		ReportManager.log("Set Chrome Options");
		ChromeOptions chromeOption = new ChromeOptions();
		chromeOption.addArguments("--incognito");
		chromeOption.addArguments("--start-maximized");
		return chromeOption;
	}

expected -> open incognito window
actual -> open normal window

**Comment by sarahelghayaty** [comment]
Dear @MohabMohie 
Thanks for letting me know , Waiting for the next release

**Comment by MohabMohie** [comment]
Dear @sarahelghayaty 
Kindly try now after upgrading to the latest release https://github.com/MohabMohie/SHAFT_ENGINE/releases/tag/6.2.20220529

**Comment by sarahelghayaty** [comment]
@MohabMohie  Thanks , it works fine now :)

**Comment by MohabMohie** [comment]
@sarahelghayaty Great news! Thanks for letting us know 🙏🏻
