### ISSUE TITLE
20220529 not working as 20220517: AcceptedW3CCapabilityKey class not found

### ISSUE THREAD

**Issue by sys123-data** [MohabMohie/SHAFT_ENGINE#623]
This version is not working as previous one.
When I am running test on Android and iOS I receive an error.

<img width="1050" alt="Screenshot 2022-06-02 at 13 37 04" src="https://user-images.githubusercontent.com/68052609/171622870-f3c51cff-ab70-4fdc-ac6b-93d8ad4bee56.png">

**Comment by MohabMohie** [comment]
should be fixed by the latest release
https://github.com/MohabMohie/SHAFT_ENGINE/releases/tag/6.2.20220609

closing for now, feel free to reopen if needed.
