### ISSUE TITLE
Automatically view allure reports.

### ISSUE THREAD

**Issue by MamdouhMansour** [MohabMohie/SHAFT_ENGINE#68]
Automatically view allure reports after finishing tests while running tests on local machine.

**Comment by MohabMohie** [comment]
As requested, here are the steps to implement this new feature. Kindly provide confirmation that you will own implementing this new feature. In that case you should fork the project > create a branch from 4.1.x > implement the feature > pull... from the latest 4.1.x from the main repo (not your fork) > open a pull request to merge your branch from your repo into 4.1.x from the main repo.

1. Create a new property named [openAllureReportAfterExecution] under execution.properties, with [true/false] possible values
![image](https://user-images.githubusercontent.com/19201898/78017644-d8c94800-734c-11ea-8301-8646748f9fe5.png)
2. Create a new method named [openAllureReportAfterExecution] under ReportManager. This method should have no inputs/outputs, and it should follow this pseudocode:
IF openAllureReportAfterExecution=true AND executionAddress=local
THEN use TerminalActions to run the generateAllureReport.bat or .sh file depending on the current OS
![image](https://user-images.githubusercontent.com/19201898/78017811-234ac480-734d-11ea-9223-26a782c0cecc.png)
3. Call the new method as the last step in the onFinish method under the SuiteListener
![image](https://user-images.githubusercontent.com/19201898/78018186-bdab0800-734d-11ea-89bb-ea8f375bcbf0.png)

Note: You can refer to ReportManager.writeGenerateReportShellFilesToProjectDirectory() to see how you can manage different OSs, and make sure to implement different commands to open the relevant files for linux/unix (.sh) and windows (.bat).

**Comment by MamdouhMansour** [comment]
Greetings Mohab,
I am confirming that implementation.

If I need to ask any question which channel would you prefer?
Regards,

    On Tuesday, March 31, 2020, 12:52:29 PM GMT+2, Mohab Mohie <notifications@github.com> wrote:  
 
 


As requested, here are the steps to implement this new feature. Kindly provide confirmation that you will own implementing this new feature. In that case you should fork the project > create a branch from 4.1.x > implement the feature > pull... from the latest 4.1.x from the main repo (not your fork) > open a pull request to merge your branch from your repo into 4.1.x from the main repo.
   
   - Create a new property named [openAllureReportAfterExecution] under execution.properties, with [true/false] possible values   

   - Create a new method named [openAllureReportAfterExecution] under ReportManager. This method should have no inputs/outputs, and it should follow this pseudocode:   
IF openAllureReportAfterExecution=true AND executionAddress=local   
THEN use TerminalActions to run the generateAllureReport.bat or .sh file depending on the current OS   

   - Call the new method as the last step in the onFinish method under the SuiteListener   


Note: You can refer to ReportManager.writeGenerateReportShellFilesToProjectDirectory() to see how you can manage different OSs, and make sure to implement different commands to open the relevant files for linux/unix (.sh) and windows (.bat).

**Comment by MohabMohie** [comment]
@MamdouhMansour kindly feel free to ask anything via messenger. And let's update the ticket by linking it to the PR once it's created.
