### ISSUE TITLE
SHAFT_Engine can skip all the elementActions validations and just log them without failing the test

### ISSUE THREAD

**Issue by MahmoudElSharkawy** [MohabMohie/SHAFT_ENGINE#77]
**Is your feature request related to a problem? Please describe.**
To make SHAFT_Engine more user friendly.

**Describe the solution you'd like**
SHAFT_Engine can skip all the **elementActions** validations and just log them without failing the test and make it optional for the user to choose to apply them or not in the **execution.property** file.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MohabMohie** [comment]
more description please :)

**Comment by MohabMohie** [comment]
since most validations are already now existing in property files then there is no more sense in doing a global setting for this.
it defeats the purpose of having SHAFT over native selenium.
