### ISSUE TITLE
when the allure report is automatically generated, the test remains stuck in the IDE

### ISSUE THREAD

**Issue by MohabMohie** [MohabMohie/SHAFT_ENGINE#80]
**Describe the bug**
The batch file is executed in attached mode and hence the IDE remains stuck waiting for the hidden batch file to finish execution

**To Reproduce**
1. Enable openAllureReportAfterExecution=true
2. Run any test
3. The report is generated and the test process is stuck in the IDE

**Expected behavior**
The IDE should finish

**Screenshots**
![image](https://user-images.githubusercontent.com/19201898/79139760-2b781a80-7db7-11ea-9c81-d311001cf4c3.png)

**Comment by MamdouhMansour** [comment]
- This bug is also reproducible with me due to that allure results couldn't be deleted.
- Tried to workaround and make (cleanAllureResultsDirectoryBeforeExecution=false).
- These lead to duplicate the test cases in the report in allure report.

**Comment by MohabMohie** [comment]
@MamdouhMansour any suggested fix? this bug is close on my to do list... could use some help though :)

**Comment by MamdouhMansour** [comment]
Sure I will try my best :D

**Comment by MohabMohie** [comment]
fix merged in #155
