### ISSUE TITLE
A listener that skip the test cases that have issues attached to them

### ISSUE THREAD

**Issue by MahmoudElSharkawy** [MohabMohie/SHAFT_ENGINE#84]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
A listener that skip the test cases that have issues attached to them and to be configurable in the properties file so the report be clean.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MohabMohie** [comment]
Those tests will be marked as skipped, but in that case how will we know if one of those tests started to pass?
To cover this case we will leave a warning to to the user, the property will be configurable, and the default will be false.

**Comment by MohabMohie** [comment]
Does the below meet your expectations @MahmoudElSharkawy ?
![image](https://user-images.githubusercontent.com/19201898/85206541-37d2a380-b323-11ea-9ad5-bbc1586d6ac4.png)
![image](https://user-images.githubusercontent.com/19201898/85206550-45882900-b323-11ea-9a72-ab3bf525d958.png)
![image](https://user-images.githubusercontent.com/19201898/85206558-520c8180-b323-11ea-8cec-f70e17284255.png)
![image](https://user-images.githubusercontent.com/19201898/85206571-62bcf780-b323-11ea-9ee1-7d21adc7d469.png)

**Comment by MahmoudElSharkawy** [comment]
@MohabMohie Yes, This is Great! This is gonna be one of the added value to SHAFT!

**Comment by MohabMohie** [comment]
It'll be pushed to the next release 👍

**Comment by MohabMohie** [comment]
The new feature will be available under platform flags and will de disabled by default
![image](https://user-images.githubusercontent.com/19201898/85212446-3a4cf180-b353-11ea-9496-22e57742bbba.png)
