### ISSUE TITLE
Logs without The ElementActions events

### ISSUE THREAD

**Issue by HaithamGitHub** [MohabMohie/SHAFT_ENGINE#87]
**Describe the bug**
no logs created in the console once set enable to alwaysLogDiscreetly=true 

**To Reproduce**
alwaysLogDiscreetly=true and run

**Expected behavior**
logs created in the console contains the ReportManager.log() only without the ElementActions events

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [[4.1.20200309]]

**Additional context**

**Comment by MohabMohie** [comment]
closed with version 4.2.20200506
