### ISSUE TITLE
Wait until the element is intractable in case of typing

### ISSUE THREAD

**Issue by asho30** [MohabMohie/SHAFT_ENGINE#89]
Framework write in the text boxes while its status "not intractable element" and after a while the element be intractable and enabled will do something like refresh and inserted data cleared.

**Comment by MohabMohie** [comment]
In case the element is not Interactable, SHAFT_Engine will attempt to type again until a certain number of attempts is expired, and if it's still not interactable it will throw an exception.

![image](https://user-images.githubusercontent.com/19201898/81674573-b8150780-944d-11ea-8772-9c35978506fa.png)

What exactly happens in that case? is an exception thrown? if so kindly provide the stacktrace and a sample test to reproduce.
